structureintel/urls.py
from django.urls import path

from . import views

app_name = "structureintel"

urlpatterns = [
    path("", views.index, name="index"),
    path("list_data", views.structureintel_list_data, name="structureintel_list_data"),
    path("add_structure/", views.CreateStructureView.as_view(), name="add_structure"),
    path("solar_system", views.solar_system, name="solar_system"),
    path("structures", views.structures, name="structures"),
    path(
        "<int:structure_id>/structure_details",
        views.structure_details,
        name="structure_details",
    ),
    path("remove/<int:pk>", views.RemoveStructureView.as_view(), name="delete"),
]

structureintel/forms.py
import re

from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.html import format_html
from eveuniverse.models import EveSolarSystem, EveType

from structureintel.models import Structure, StructureModule


class StructureForm(forms.ModelForm):
    ASTERISK_HTML = '<i class="fas fa-asterisk"></i>'

    eve_solar_system_2 = forms.CharField(
        required=True,
        label=format_html(f"Solar System {ASTERISK_HTML}"),
        widget=forms.Select(attrs={"class": "select2-solar-systems"}),
    )
    eve_structure_type_2 = forms.CharField(
        required=True,
        label=format_html(f"Structure Type {ASTERISK_HTML}"),
        widget=forms.Select(attrs={"class": "select2-structure-types"}),
    )
    mode = forms.ChoiceField(
        required=True, choices=Structure.PowerMode.choices, widget=forms.Select()
    )
    reinforcement_hour = forms.IntegerField(
        required=True,
        validators=[MinValueValidator(0), MaxValueValidator(23)],
        widget=forms.NumberInput(attrs={"min": 0, "max": 23}),
    )
    fitting = forms.CharField(required=True, widget=forms.Textarea(attrs={"rows": 5}))

    field_order = [
        "eve_solar_system_2",
        "eve_structure_type_2",
        "name",
        "owner",
        "mode",
        "reinforcement_hour",
        "fitting",
    ]

    class Meta:
        model = Structure
        fields = {
            "eve_solar_system_2",
            "eve_structure_type_2",
            "name",
            "owner",
            "mode",
            "reinforcement_hour",
            "fitting",
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        if "instance" in kwargs and kwargs["instance"] is not None:
            my_instance = kwargs["instance"]
            self.is_new = False
        else:
            my_instance = None
            self.is_new = True

        super().__init__(*args, **kwargs)
        if my_instance:
            self.fields["eve_solar_system_2"].widget.choices = [
                (
                    str(my_instance.eve_solar_system_id),
                    my_instance.eve_solar_system.name,
                )
            ]
            self.fields["eve_structure_type_2"].widget.choices = [
                (str(my_instance.structure_type_id), my_instance.structure_type.name)
            ]

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get("eve_solar_system_2"):
            try:
                solar_system = EveSolarSystem.objects.get(
                    id=cleaned_data["eve_solar_system_2"]
                )
            except EveSolarSystem.DoesNotExist:
                pass
            else:
                self.fields["eve_solar_system_2"].widget.choices = [
                    (str(solar_system.id), solar_system.name)
                ]

        if cleaned_data.get("eve_structure_type_2"):
            try:
                structure_type = EveType.objects.get(
                    id=cleaned_data["eve_structure_type_2"]
                )
            except EveType.DoesNotExist:
                pass
            else:
                self.fields["eve_structure_type_2"].widget.choices = [
                    (str(structure_type.id), structure_type.name)
                ]

    def save(self, commit=True):
        # Store default fields
        structure: Structure = super().save(commit=False)
        # Store custom fields
        structure.power_mode = self.cleaned_data.get("mode")
        structure.eve_solar_system_id = self.cleaned_data.get("eve_solar_system_2")
        structure.eve_type_id = self.cleaned_data.get("eve_structure_type_2")
        structure.reinforce_hour = self.cleaned_data.get("reinforcement_hour")
        fitting = self.cleaned_data.get("fitting")
        # Parse fitting
        fitting_data = fitting.replace("\r\n", "\n")
        highslots = None
        # Fitting has high slots
        if "High Power Slots" in fitting_data:
            # Assume High and Med slots are fitted
            highslots = re.search(
                "High Power Slots\n(.*?)Medium Power Slots", fitting_data, re.M | re.S
            )
            if not highslots:
                # Assume High and Low slots are fitted
                highslots = re.search(
                    "High Power Slots\n(.*?)Low Power Slots", fitting_data, re.M | re.S
                )
                if not highslots:
                    # Assume High and Rig slots are fitted
                    highslots = re.search(
                        "High Power Slots\n(.*?)Rig Slots", fitting_data, re.M | re.S
                    )
                    if not highslots:
                        # Assume High and Service slots are fitted
                        highslots = re.search(
                            "High Power Slots\n(.*?)Service Slots",
                            fitting_data,
                            re.M | re.S,
                        )
                        if not highslots:
                            highslots = fitting_data.replace("High Power Slots\n", "")
        if type(highslots) == re.Match:
            highslots = highslots.group(1)

        mediumslots = None
        # Fitting has med slots
        if "Medium Power Slots" in fitting_data:
            # Assume Medium and Low slots are fitted
            mediumslots = re.search(
                "Medium Power Slots\n(.*?)Low Power Slots", fitting_data, re.M | re.S
            )
            if not mediumslots:
                # Assume Medium and Low slots are fitted
                mediumslots = re.search(
                    "Medium Power Slots\n(.*?)Rig Slots", fitting_data, re.M | re.S
                )
                if not mediumslots:
                    # Assume Medium and Rig slots are fitted
                    mediumslots = re.search(
                        "Medium Power Slots\n(.*?)Service Slots",
                        fitting_data,
                        re.M | re.S,
                    )
                    if not mediumslots:
                        mediumslots = fitting_data.replace("Medium Power Slots\n", "")
        if type(mediumslots) == re.Match:
            mediumslots = mediumslots.group(1)

        lowslots = None
        # Fitting has low slots
        if "Low Power Slots" in fitting_data:
            # Assume Low and rig slots are fitted
            lowslots = re.search(
                "Low Power Slots\n(.*?)Rig Slots", fitting_data, re.M | re.S
            )
            if not lowslots:
                # Assume Low and Service slots are fitted
                lowslots = re.search(
                    "Low Power Slots\n(.*?)Service Slots", fitting_data, re.M | re.S
                )
                if not lowslots:
                    lowslots = fitting_data.replace("Low Power Slots\n", "")
        if type(lowslots) == re.Match:
            lowslots = lowslots.group(1)

        rigslots = None
        # Fitting has rig slots
        if "Rig Slots" in fitting_data:
            # Assume Rig and Service slots are fitted
            rigslots = re.search(
                "Rig Slots\n(.*?)Service Slots", fitting_data, re.M | re.S
            )
            if not rigslots:
                rigslots = fitting_data.replace("Low Power Slots\n", "")
        if type(rigslots) == re.Match:
            rigslots = rigslots.group(1)

        serviceslots = None
        # Fitting has service slots
        if "Service Slots" in fitting_data:
            serviceslots = fitting_data.split("Service Slots\n")[1]

        # Save structure so related objects can be stored
        if commit:
            structure.save()

        # Store fitting mods

        if highslots:
            modules = highslots.strip().split("\n")
            for module in modules:
                evemodule = EveType.objects.get(name=module)
                fittingmodule = StructureModule()
                fittingmodule.eve_type_id = evemodule.id
                fittingmodule.slot = StructureModule.Slot.HIGHSLOT
                fittingmodule.structure_id = structure.id
                fittingmodule.save()

        if mediumslots:
            modules = mediumslots.strip().split("\n")
            for module in modules:
                evemodule = EveType.objects.get(name=module)
                fittingmodule = StructureModule()
                fittingmodule.eve_type_id = evemodule.id
                fittingmodule.slot = StructureModule.Slot.MEDSLOT
                fittingmodule.structure_id = structure.id
                fittingmodule.save()

        if lowslots:
            modules = lowslots.strip().split("\n")
            for module in modules:
                evemodule = EveType.objects.get(name=module)
                fittingmodule = StructureModule()
                fittingmodule.eve_type_id = evemodule.id
                fittingmodule.slot = StructureModule.Slot.LOWSLOT
                fittingmodule.structure_id = structure.id
                fittingmodule.save()

        if rigslots:
            modules = rigslots.strip().split("\n")
            for module in modules:
                evemodule = EveType.objects.get(name=module)
                fittingmodule = StructureModule()
                fittingmodule.eve_type_id = evemodule.id
                fittingmodule.slot = StructureModule.Slot.RIGSLOT
                fittingmodule.structure_id = structure.id
                fittingmodule.save()

        if serviceslots:
            modules = serviceslots.strip().split("\n")
            for module in modules:
                evemodule = EveType.objects.get(name=module)
                fittingmodule = StructureModule()
                fittingmodule.eve_type_id = evemodule.id
                fittingmodule.slot = StructureModule.Slot.SERVICE
                fittingmodule.structure_id = structure.id
                fittingmodule.save()
        return structure

structureintel/templates/structureintel/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "StructureIntel" %}{% endblock %}

{% block content %}
    <div class="structureintel">
        <h1 class="page-header text-center">{% translate "StructureIntel" %}</h1>

        {% block details %}{% endblock %}
    </div>
{% endblock %}

structureintel/templates/structureintel/index.html
{% extends 'structureintel/base.html' %}
{% load i18n %}
{% load bootstrap %}
{% load static %}
{% load humanize %}

{% block details %}

    <span class="pull-right" style="margin-bottom: 5px;">
        <a href="{% url 'structureintel:add_structure' %}" class="btn btn-success">Add structure</a>

    </span>

    <table id="structureintel--table" style="width:100%" class="table table-striped table-compact">
        <thead>
            <th>{% translate "Location"%}</th>
            <th></th>
            <th>{% translate "Type" %}</th>
            <th>{% translate "Name & Owner" %}</th>
            <th>{% translate "Services" %}</th>
            <th>{% translate "Power" %}</th>
            <th>{% translate "R-Hour" %}</th>
            <th></th>
        </thead>
    </table>

    <div class="modal" id="modalStructureDetails" tabindex="-1" role="dialog" aria-labelledby="{% translate 'modalStructureDetails '%}">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modalStructureDetailsContent">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Loading...</h4>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_javascript %}
{% include 'bundles/datatables-js.html' %}
<script type="application/javascript" src="{% static 'js/filterDropDown/filterDropDown.min.js' %}"></script>
<script type="application/javascript">
$(document).ready(function () {
    $('#modalStructureDetails').on('show.bs.modal', function(event) {
        $(this).find('.modal-title').html('Loading...');
        {% if NIGHT_MODE %}
            $(this).find('.modal-body').html('<img src="{% static "structureintel/img/Spinner-1s-64px-dark.gif" %}">');
        {% else %}
            $(this).find('.modal-body').html('<img src="{% static "structureintel/img/Spinner-1s-64px-light.gif" %}">');
        {% endif %}

        const button = $(event.relatedTarget);
        const ajax_url = button.data('ajax_url');
        $("#modalStructureDetailsContent").load(
            ajax_url, null, (response, status, xhr) => {
                if (status != 'success') {
                    $(this).find('.modal-title').html('Error');
                    $(this).find('.modal-body').html(
                        `<p class="text-danger">${xhr.status} ${xhr.statusText}</p>`
                    );
                }
            }
        );
    });

    $('#structureintel--table').DataTable({
        ajax: {
            url: "{% url 'structureintel:structureintel_list_data' %}",
            dataSrc: 'data',
            cache: false
        },
        columns: [
            { data: 'location' },
            { data: 'type_icon', width: "40px" },
            { data: 'type' },
            { data: 'structure_name' },
            { data: 'services' },
            { data: 'power' },
            { data: 'reinforcement' },
            { data: 'actions'},
            /* hidden */
            { data: 'system_name'},
            { data: 'constellation_name'},
            { data: 'region_name'}
        ],
        lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
        columnDefs: [
                    { "sortable": false, "targets": [ 1, 6 ] },
                    { "visible": false, "targets": [8, 9, 10] }
        ],
        bootstrap: true,
        filterDropDown:
        {
            columns: [
                {
                    idx: 2,
                    title: "{% translate 'Structure' %}"
                },
                {
                    idx: 5,
                    title: "{% translate 'State' %}"
                },
                {
                    idx: 8,
                    title: "{% translate 'Solar system' %}"
                },
                {
                    idx: 9,
                    title: "{% translate 'Constellation' %}"
                },
                {
                    idx: 10,
                    title: "{% translate 'Region' %}"
                }
            ]
        }
    });
})

</script>
{% endblock %}

{% block extra_css %}
{% include 'bundles/datatables-css.html' %}
<style>
#structureintel--table_filter {
    text-align: right;
}
#structureintel--table tbody td, #structureintel--table thead th {
    text-align: center;
    vertical-align: middle;
    word-wrap: break-word;
}
</style>
{% endblock %}

{% block extra_script %}
{% endblock %}

structureintel/templates/structureintel/structure_confirm_delete.html
{% extends "allianceauth/base.html" %}
{% load i18n %}

{% block page_title %}Delete Structure{% endblock page_title %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
        <h1 class="page-header text-center">
            Delete Structure
        </h1>
        <div class="container-fluid">
            <div class="row">
                <form action="" method="post" id="confirm-delete-form">
                    {% csrf_token %}
                    <p>
                        Are you sure you want to delete this structure?
                    </p>
                    <p>
                        <strong>{{ object }}</strong>
                    </p>
                    <input class="btn btn-danger" type="submit" value="Delete" />
                    <a href="{% url 'structureintel:index' %}" class="btn btn-default">Cancel</a>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

structureintel/templates/structureintel/structure_create_form.html
{% extends "structureintel/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% block details %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form role="form" action="" method="POST">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <a href="{% url 'structureintel:index' %}" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-success pull-right">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock details %}

{% block extra_css %}
    <link href="{% static 'structureintel/vendor/select2/select2.min.css' %}" rel="stylesheet" />
    <link href="{% static 'structureintel/vendor/select2-bootstrap-theme/select2-bootstrap.min.css' %}" rel="stylesheet" />
    <style>
        .form-group.required label:after {
            content:"*";
            color:red;
        }
        .select2-dropdown {
            color: rgb(44, 62, 80);
        }
        #fitting {
            resize: vertical;
        }
        .fa-asterisk {
            color: salmon;
            font-size: 0.75rem;
            vertical-align: top;
        }

    </style>
{% endblock extra_css %}

{% block extra_javascript %}
    <script type="application/javascript" src="{% static 'structureintel/vendor/select2/select2.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $(document).on('select2:open', () => {
                document.querySelector('.select2-search__field').focus();
              });
            $('#id_eve_solar_system_2').select2({
                ajax: {
                    url: '{% url 'structureintel:solar_system' %}',
                    dataType: 'json',
                    processResults: function (data) {
                        return {
                          results: data.data
                        };
                      }
                },
                theme: "bootstrap"
            })
            $('#id_eve_structure_type_2').select2({
                ajax: {
                    url: '{% url 'structureintel:structures' %}',
                    dataType: 'json',
                    processResults: function (data) {
                        return {
                          results: data.data
                        };
                      }
                },
                theme: "bootstrap"
            })
            $('#reinforcement').select2({
                theme: "bootstrap"
            })
        })
    </script>
{% endblock extra_javascript %}